[package]
name = "project-x"
version = "0.1.0"
edition = "2021"
description = "AI-First Coding Assistant (Rust Edition)"
authors = ["Your Name <your.email@example.com>"]

[dependencies]

reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["rt-multi-thread", "macros"] }

[[bin]]
name = "project-x"
path = "src/main.rs"
